#!/bin/sh

mkdir results 2>/dev/null

find hello-boot/ -type f -name '*.gradle' -or -name '*.java' |xargs wc -lw >>results/code
echo >>results/code

find hello-sabina/ -type f -name '*.gradle' -or -name '*.java' |xargs wc -lw >>results/code
echo >>results/code
